USE [master]
GO

/****** Object:  Database [Sistema_de_Nomina]    Script Date: 8/15/2019 1:43:06 PM ******/
CREATE DATABASE [Sistema_de_Nomina]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Sistema_de_Nomina', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Sistema_de_Nomina.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Sistema_de_Nomina_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Sistema_de_Nomina_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Sistema_de_Nomina] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Sistema_de_Nomina].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Sistema_de_Nomina] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Sistema_de_Nomina] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Sistema_de_Nomina] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Sistema_de_Nomina] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Sistema_de_Nomina] SET ARITHABORT OFF 
GO

ALTER DATABASE [Sistema_de_Nomina] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Sistema_de_Nomina] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Sistema_de_Nomina] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Sistema_de_Nomina] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Sistema_de_Nomina] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Sistema_de_Nomina] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Sistema_de_Nomina] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Sistema_de_Nomina] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Sistema_de_Nomina] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Sistema_de_Nomina] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Sistema_de_Nomina] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Sistema_de_Nomina] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Sistema_de_Nomina] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Sistema_de_Nomina] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Sistema_de_Nomina] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Sistema_de_Nomina] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Sistema_de_Nomina] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Sistema_de_Nomina] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Sistema_de_Nomina] SET  MULTI_USER 
GO

ALTER DATABASE [Sistema_de_Nomina] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Sistema_de_Nomina] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Sistema_de_Nomina] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Sistema_de_Nomina] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Sistema_de_Nomina] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Sistema_de_Nomina] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Sistema_de_Nomina] SET  READ_WRITE 
GO

